# Generated by Django 2.2.7 on 2019-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20191202_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=50)),
            ],
        ),
        migrations.DeleteModel(
            name='sightings',
        ),
    ]
