# Generated by Django 2.2.7 on 2019-12-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20191202_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sighting',
        ),
    ]
