# Generated by Django 2.2.7 on 2019-12-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_sighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Hectare',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Latitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Longitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Other_Activities',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Primary_Fur_Color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Shift',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Specific_Location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
