# Generated by Django 2.2.7 on 2019-12-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=50, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=50, max_digits=50)),
                ('Unique_Squirrel_ID', models.CharField(max_length=50)),
                ('Hectare', models.CharField(max_length=50)),
                ('Shift', models.CharField(max_length=50)),
                ('Date', models.DateTimeField()),
                ('Age', models.CharField(max_length=50)),
                ('Primary_Fur_Color', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Specific_Location', models.CharField(max_length=50)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(max_length=50)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twiches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
            ],
        ),
    ]
